USE master;
GO
ALTER DATABASE qlgamee SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'qlgamee')
    DROP DATABASE qlgamee;
GO
CREATE DATABASE qlgamee;
GO
USE qlgamee;
GO

-- ============================================================
-- TAO BANG
-- ============================================================

CREATE TABLE ROLE (
    MaRole  INT IDENTITY(1,1) PRIMARY KEY,
    TenRole NVARCHAR(50) NOT NULL
);

CREATE TABLE NHANVIEN (
    MaNV       INT IDENTITY(1,1) PRIMARY KEY,
    HoTen      NVARCHAR(100) NOT NULL,
    SDT        VARCHAR(15),
    NgaySinh   DATE,
    CCCD       VARCHAR(20) UNIQUE,
    NgayVaoLam DATE DEFAULT GETDATE(),
    IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE USERS (
    MaUser   INT IDENTITY(1,1) PRIMARY KEY,
    Username VARCHAR(50)  UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    MaRole   INT,
    MaNV     INT
);

CREATE TABLE KHACHHANG (
    MaKH        INT IDENTITY(1,1) PRIMARY KEY,
    HoTen       NVARCHAR(100),
    SDT         VARCHAR(15),
    CCCD        VARCHAR(20),
    Email       VARCHAR(100),
    DiaChi      NVARCHAR(200),
    DiemTichLuy INT DEFAULT 0,
    IsDeleted BIT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX UQ_KHACHHANG_SDT
ON KHACHHANG (SDT)
WHERE SDT IS NOT NULL;

CREATE TABLE GAME (
    MaGame  INT IDENTITY(1,1) PRIMARY KEY,
    TenGame NVARCHAR(200) NOT NULL,
    TheLoai NVARCHAR(50),
    NenTang NVARCHAR(50),
    GhiChu  NVARCHAR(500),
    HinhAnh VARCHAR(255),
    IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE GAME_CHITIET (
    MaGame         INT PRIMARY KEY,
    MoTa           NVARCHAR(MAX),
    Rating         NVARCHAR(50),
    Genre          NVARCHAR(100),
    DeliveryMethod NVARCHAR(50),
    ReleaseDate    DATE,
    Region         NVARCHAR(50),
    Features       NVARCHAR(200),
    Language       NVARCHAR(200),
    Currency       NVARCHAR(10)
);

CREATE TABLE SANPHAM (
    MaSP        INT IDENTITY(1,1) PRIMARY KEY,
    MaGame      INT,
    GiaBan      DECIMAL(15,2),
    GiaThueNgay DECIMAL(15,2),
    IsDeleted BIT NOT NULL DEFAULT 0
);

-- TrangThai: SanSang | DangThue | DaBan | Hong
CREATE TABLE CD (
    MaCD      INT IDENTITY(1,1) PRIMARY KEY,
    MaSP      INT,
    TinhTrang NVARCHAR(50),
    TrangThai NVARCHAR(20) DEFAULT N'SanSang',
    IsDeleted BIT NOT NULL DEFAULT 0
);

CREATE TABLE ROM (
    MaSP       INT PRIMARY KEY,
    DungLuong  NVARCHAR(20),
    LinkLuuTru VARCHAR(500),
    SoLuotBan  INT DEFAULT 0,
    IsDeleted BIT NOT NULL DEFAULT 0
);

-- TrangThai: ChuaThanhToan | DaThanhToan
CREATE TABLE HOADON (
    MaHD       INT IDENTITY(1,1) PRIMARY KEY,
    MaKH       INT,
    MaNV       INT,
    NgayLap    DATETIME DEFAULT GETDATE(),
    TongTien   DECIMAL(15,2) DEFAULT 0,
    DiemSuDung INT DEFAULT 0,
    TienGiam   DECIMAL(15,2) DEFAULT 0,
    TrangThai  NVARCHAR(20) DEFAULT N'ChuaThanhToan'
);

CREATE TABLE CTHOADON (
    MaHD    INT,
    MaSP    INT,
    SoLuong INT,
    DonGia  DECIMAL(15,2),
    PRIMARY KEY (MaHD, MaSP)
);

-- TrangThai: DangThue | DaTra
CREATE TABLE PHIEUTHUE (
    MaPT          INT IDENTITY(1,1) PRIMARY KEY,
    MaKH          INT,
    NgayThue      DATETIME DEFAULT GETDATE(),
    NgayTraDuKien DATETIME,
    NgayTraThucTe DATETIME,
    TienCoc       DECIMAL(15,2),
    TienPhat      DECIMAL(15,2) DEFAULT 0,
    TrangThai     NVARCHAR(20) DEFAULT N'DangThue'
);

CREATE TABLE CTPHIEUTHUE (
    MaPT       INT,
    MaCD       INT,
    MaNV       INT,
    DonGiaThue DECIMAL(15,2),
    PRIMARY KEY (MaPT, MaCD)
);

-- Loai: 'CONG' hoac 'TRU'
CREATE TABLE DIEM_LICHSU (
    MaLS   INT IDENTITY(1,1) PRIMARY KEY,
    MaKH   INT,
    MaPT   INT,
    Loai   NVARCHAR(10),
    SoDiem INT,
    Ngay   DATETIME DEFAULT GETDATE(),
    GhiChu NVARCHAR(200)
);
GO

-- ============================================================
-- FOREIGN KEY
-- ============================================================

ALTER TABLE USERS
ADD CONSTRAINT FK_USERS_ROLE
FOREIGN KEY (MaRole) REFERENCES ROLE(MaRole);

ALTER TABLE USERS
ADD CONSTRAINT FK_USERS_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE GAME_CHITIET
ADD CONSTRAINT FK_GAMECHITIET_GAME
FOREIGN KEY (MaGame) REFERENCES GAME(MaGame);

ALTER TABLE SANPHAM
ADD CONSTRAINT FK_SANPHAM_GAME
FOREIGN KEY (MaGame) REFERENCES GAME(MaGame);

ALTER TABLE CD
ADD CONSTRAINT FK_CD_SANPHAM
FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);

ALTER TABLE ROM
ADD CONSTRAINT FK_ROM_SANPHAM
FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE CTHOADON
ADD CONSTRAINT FK_CTHOADON_HOADON
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE CTHOADON
ADD CONSTRAINT FK_CTHOADON_SANPHAM
FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);

ALTER TABLE PHIEUTHUE
ADD CONSTRAINT FK_PHIEUTHUE_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE CTPHIEUTHUE
ADD CONSTRAINT FK_CTPHIEUTHUE_PHIEUTHUE
FOREIGN KEY (MaPT) REFERENCES PHIEUTHUE(MaPT);

ALTER TABLE CTPHIEUTHUE
ADD CONSTRAINT FK_CTPHIEUTHUE_CD
FOREIGN KEY (MaCD) REFERENCES CD(MaCD);

ALTER TABLE CTPHIEUTHUE
ADD CONSTRAINT FK_CTPHIEUTHUE_NHANVIEN
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE DIEM_LICHSU
ADD CONSTRAINT FK_DIEMLICHSU_KHACHHANG
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE DIEM_LICHSU
ADD CONSTRAINT FK_DIEMLICHSU_PHIEUTHUE
FOREIGN KEY (MaPT) REFERENCES PHIEUTHUE(MaPT);