-- ========================
-- 1. ROLE
-- ========================
CREATE TABLE ROLE (
    MaRole NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenRole VARCHAR2(50) NOT NULL
);

-- ========================
-- 2. NHANVIEN
-- ========================
CREATE TABLE NHANVIEN (
    MaNV NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HoTen VARCHAR2(100) NOT NULL,
    SDT VARCHAR2(15),
    NgaySinh DATE,
    CCCD VARCHAR2(20) UNIQUE,
    NgayVaoLam DATE DEFAULT CURRENT_DATE
);

-- ========================
-- 3. USERS
-- ========================
CREATE TABLE USERS (
    MaUser NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(50) UNIQUE NOT NULL,
    Password VARCHAR2(255) NOT NULL,
    MaRole NUMBER,
    MaNV NUMBER
);

-- ========================
-- 4. KHACHHANG (HỖ TRỢ TÍCH ĐIỂM)
-- ========================
CREATE TABLE KHACHHANG (
    MaKH NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    HoTen VARCHAR2(100),
    SDT VARCHAR2(15) UNIQUE,
    CCCD VARCHAR2(20),
    Email VARCHAR2(100),
    DiaChi VARCHAR2(200),
    DiemTichLuy NUMBER DEFAULT 0
);

-- ========================
-- 5. GAME
-- ========================
CREATE TABLE GAME (
    MaGame NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenGame VARCHAR2(200) NOT NULL,
    TheLoai VARCHAR2(50),
    NenTang VARCHAR2(50),
    GhiChu VARCHAR2(500);
);

-- ========================
-- 6. SANPHAM (LOẠI SẢN PHẨM)
-- ========================
CREATE TABLE SANPHAM (
    MaSP NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaGame NUMBER,
    GiaBan NUMBER(15,2),
    GiaThueNgay NUMBER(15,2)
);

-- ========================
-- 7. CD (TỪNG ĐĨA RIÊNG BIỆT)
-- ========================
CREATE TABLE CD (
    MaCD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaSP NUMBER,
    TinhTrang VARCHAR2(50),
    TrangThai VARCHAR2(20) DEFAULT 'SanSang'
    -- SanSang / DangThue / Hong
);

-- ========================
-- 8. ROM (DIGITAL - 1 SP = 1 ROM)
-- ========================
CREATE TABLE ROM (
    MaSP NUMBER PRIMARY KEY,
    DungLuong VARCHAR2(20),
    LinkLuuTru VARCHAR2(500),
    SoLuotBan NUMBER DEFAULT 0
);

-- ========================
-- 9. HOADON (BÁN HÀNG)
-- ========================
CREATE TABLE HOADON (
    MaHD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaKH NUMBER,
    MaNV NUMBER,
    NgayLap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TongTien NUMBER(15,2) DEFAULT 0,

    DiemSuDung NUMBER DEFAULT 0,
    TienGiam NUMBER(15,2) DEFAULT 0,

    TrangThai VARCHAR2(20) DEFAULT 'ChuaThanhToan'
);

-- ========================
-- 10. CTHOADON
-- ========================
CREATE TABLE CTHOADON (
    MaHD NUMBER,
    MaSP NUMBER,
    SoLuong NUMBER,
    DonGia NUMBER(15,2),
    PRIMARY KEY (MaHD, MaSP)
);

-- ========================
-- 11. PHIEUTHUE (THUÊ CD)
-- ========================
CREATE TABLE PHIEUTHUE (
    MaPT NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaKH NUMBER,
    NgayThue TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayTraDuKien TIMESTAMP,
    NgayTraThucTe TIMESTAMP,
    TienCoc NUMBER(15,2),
    TienPhat NUMBER(15,2) DEFAULT 0,
    TrangThai VARCHAR2(20) DEFAULT 'DangThue'
);

-- ========================
-- 12. CTPHIEUTHUE (THUÊ THEO CD)
-- ========================
CREATE TABLE CTPHIEUTHUE (
    MaPT NUMBER,
    MaCD NUMBER,
    DonGiaThue NUMBER(15,2),
    PRIMARY KEY (MaPT, MaCD)
);

-- ========================
-- 13. DIEM_LICHSU
-- ========================
CREATE TABLE DIEM_LICHSU (
    MaLS NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MaKH NUMBER,
    Loai VARCHAR2(10), -- Cong / Tru
    SoDiem NUMBER,
    Ngay TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    GhiChu VARCHAR2(200)
);

-- ========================
-- FOREIGN KEY
-- ========================

ALTER TABLE USERS 
ADD CONSTRAINT FK_USERS_ROLE 
FOREIGN KEY (MaRole) REFERENCES ROLE(MaRole);

ALTER TABLE USERS 
ADD CONSTRAINT FK_USERS_NV 
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE SANPHAM 
ADD CONSTRAINT FK_SP_GAME 
FOREIGN KEY (MaGame) REFERENCES GAME(MaGame);

ALTER TABLE CD 
ADD CONSTRAINT FK_CD_SP 
FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);

ALTER TABLE ROM 
ADD CONSTRAINT FK_ROM_SP 
FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);

ALTER TABLE HOADON 
ADD CONSTRAINT FK_HD_KH 
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE HOADON 
ADD CONSTRAINT FK_HD_NV 
FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV);

ALTER TABLE CTHOADON 
ADD CONSTRAINT FK_CTHD_HD 
FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD);

ALTER TABLE CTHOADON 
ADD CONSTRAINT FK_CTHD_SP 
FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP);

ALTER TABLE PHIEUTHUE 
ADD CONSTRAINT FK_PT_KH 
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);

ALTER TABLE CTPHIEUTHUE 
ADD CONSTRAINT FK_CTPT_PT 
FOREIGN KEY (MaPT) REFERENCES PHIEUTHUE(MaPT);

ALTER TABLE CTPHIEUTHUE 
ADD CONSTRAINT FK_CTPT_CD 
FOREIGN KEY (MaCD) REFERENCES CD(MaCD);

ALTER TABLE DIEM_LICHSU
ADD CONSTRAINT FK_DIEM_KH
FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);