CREATE DATABASE GameStoreManager;
USE GameStoreManager;
GO

CREATE TABLE ROLE (
    MaRole INT PRIMARY KEY IDENTITY(1,1),
    TenRole NVARCHAR(50) NOT NULL
);

CREATE TABLE [USER] ( 
    Username VARCHAR(50) PRIMARY KEY,
    Password VARCHAR(255) NOT NULL,
    MaRole INT,
    HoTen NVARCHAR(100),
    CONSTRAINT FK_User_Role FOREIGN KEY (MaRole) REFERENCES ROLE(MaRole)
);

CREATE TABLE KHACHHANG (
    MaKH CHAR(10) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15),
    Email VARCHAR(100),
    DiaChi NVARCHAR(255)
);

CREATE TABLE GAME (
    MaGame CHAR(10) PRIMARY KEY,
    TenGame NVARCHAR(200) NOT NULL,
    TheLoai NVARCHAR(50),
    NenTang NVARCHAR(50),
    GiaBan DECIMAL(18, 2),
    GiaThueNgay DECIMAL(18, 2)
);

CREATE TABLE SANPHAM (
    MaSP CHAR(15) PRIMARY KEY,
    MaGame CHAR(10),
    GiaBan DECIMAL(18, 2),
    LoaiSP VARCHAR(10) CHECK (LoaiSP IN ('CD', 'ROM')), 
    CONSTRAINT FK_SP_Game FOREIGN KEY (MaGame) REFERENCES GAME(MaGame)
);

CREATE TABLE CD (
    MaSP CHAR(15) PRIMARY KEY,
    TinhTrang NVARCHAR(50),
    CONSTRAINT FK_CD_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE ROM (
    MaSP CHAR(15) PRIMARY KEY,
    DungLuong VARCHAR(20),
    LinkLuuTru VARCHAR(255),
    SoLuotBan INT DEFAULT 0,
    CONSTRAINT FK_ROM_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE HOADON (
    MaHD CHAR(15) PRIMARY KEY,
    MaKH CHAR(10),
    NgayLap DATETIME DEFAULT GETDATE(),
    TongTien DECIMAL(18, 2) DEFAULT 0,
    CONSTRAINT FK_HD_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE CTHOADON (
    MaHD CHAR(15),
    MaSP CHAR(15),
    SoLuong INT,
    DonGia DECIMAL(18, 2),
    PRIMARY KEY (MaHD, MaSP),
    CONSTRAINT FK_CTHD_HD FOREIGN KEY (MaHD) REFERENCES HOADON(MaHD),
    CONSTRAINT FK_CTHD_SP FOREIGN KEY (MaSP) REFERENCES SANPHAM(MaSP)
);

CREATE TABLE PHIEUTHUE (
    MaPT CHAR(15) PRIMARY KEY,
    MaKH CHAR(10),
    NgayThue DATETIME,
    NgayTraDuKien DATETIME,
    NgayTraThucTe DATETIME,
    TienCoc DECIMAL(18, 2),
    TienPhat DECIMAL(18, 2) DEFAULT 0,
    CONSTRAINT FK_PT_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH)
);

CREATE TABLE CTPHIEUTHUE (
    MaPT CHAR(15),
    MaSP CHAR(15),
    PRIMARY KEY (MaPT, MaSP),
    CONSTRAINT FK_CTPT_PT FOREIGN KEY (MaPT) REFERENCES PHIEUTHUE(MaPT),
    CONSTRAINT FK_CTPT_CD FOREIGN KEY (MaSP) REFERENCES CD(MaSP)
);
