-- Sequence cho các bảng chính
CREATE SEQUENCE SEQ_KHACHHANG START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GAME      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SANPHAM   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_HOADON    START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PHIEUTHUE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USERS     START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ROLE      START WITH 1 INCREMENT BY 1;

-- Tự động tăng cho KHACHHANG
CREATE OR REPLACE TRIGGER TRG_ID_KHACHHANG
BEFORE INSERT ON KHACHHANG FOR EACH ROW
BEGIN
    IF :NEW.MaKH IS NULL THEN
        SELECT SEQ_KHACHHANG.NEXTVAL INTO :NEW.MaKH FROM DUAL;
    END IF;
END;
/

-- Tự động tăng cho GAME
CREATE OR REPLACE TRIGGER TRG_ID_GAME
BEFORE INSERT ON GAME FOR EACH ROW
BEGIN
    IF :NEW.MaGame IS NULL THEN
        SELECT SEQ_GAME.NEXTVAL INTO :NEW.MaGame FROM DUAL;
    END IF;
END;
/

-- Tự động tăng cho HOADON
CREATE OR REPLACE TRIGGER TRG_ID_HOADON
BEFORE INSERT ON HOADON FOR EACH ROW
BEGIN
    IF :NEW.MaHD IS NULL THEN
        SELECT SEQ_HOADON.NEXTVAL INTO :NEW.MaHD FROM DUAL;
    END IF;
END;
/

-- Tự động tăng cho PHIEUTHUE
CREATE OR REPLACE TRIGGER TRG_ID_PHIEUTHUE
BEFORE INSERT ON PHIEUTHUE FOR EACH ROW
BEGIN
    IF :NEW.MaPT IS NULL THEN
        SELECT SEQ_PHIEUTHUE.NEXTVAL INTO :NEW.MaPT FROM DUAL;
    END IF;
END;
/
-- Tự động tính tiền phạt
-- Tự động tăng cho USERS
CREATE OR REPLACE TRIGGER TRG_ID_USERS
BEFORE INSERT ON USERS FOR EACH ROW
BEGIN
    IF :NEW.MaUser IS NULL THEN
        SELECT SEQ_USERS.NEXTVAL INTO :NEW.MaUser FROM DUAL;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER TRG_TINH_TIEN_PHAT
BEFORE UPDATE OF NgayTraThucTe ON PHIEUTHUE
FOR EACH ROW
DECLARE
    v_so_ngay_tre NUMBER;
BEGIN
    -- Chỉ tính khi khách mang máy/đĩa đến trả (có NgayTraThucTe)
    IF :NEW.NgayTraThucTe IS NOT NULL THEN
        -- So sánh ngày trả thực tế với ngày trả dự kiến
        IF :NEW.NgayTraThucTe > :OLD.NgayTraDuKien THEN
            -- Tính số ngày chênh lệch (Làm tròn lên bằng CEIL)
            v_so_ngay_tre := CEIL(CAST(:NEW.NgayTraThucTe AS DATE) - CAST(:OLD.NgayTraDuKien AS DATE));
            
            -- Gán số tiền phạt (Ví dụ phạt 20.000đ mỗi ngày trễ)
            :NEW.TienPhat := v_so_ngay_tre * 20000;
        ELSE
            -- Nếu trả đúng hạn hoặc sớm hơn thì tiền phạt bằng 0
            :NEW.TienPhat := 0;
        END IF;
    END IF;
END;
/
